# Generated by Django 5.2.12 on 2026-04-22 22:29

import django.db.models.deletion
import taggit.managers
import utilities.fields
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0122_charfield_null_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('scope_type', models.CharField(default='hall', max_length=32)),
                ('upstream_supply_type', models.CharField(default='ac', max_length=16)),
                ('nominal_distribution_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('frequency_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_template_derived', models.BooleanField(default=False)),
                ('design_state', models.CharField(default='planned', max_length=32)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_systems', to='dcim.location')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_systems', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'power system',
                'verbose_name_plural': 'power systems',
                'ordering': ('site__name', 'name'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PowerDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(max_length=32)),
                ('kind', models.CharField(default='primary', max_length=32)),
                ('color', utilities.fields.ColorField(blank=True, max_length=6)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('failure_isolation_depth', models.PositiveSmallIntegerField(default=0)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_domains', to='netbox_power_plant.powersystem')),
            ],
            options={
                'verbose_name': 'power domain',
                'verbose_name_plural': 'power domains',
                'ordering': ('power_system__name', 'priority', 'code', 'name'),
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RedundancyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('topology_type', models.CharField(default='none', max_length=32)),
                ('min_distinct_paths', models.PositiveSmallIntegerField(default=1)),
                ('requires_domain_isolation', models.BooleanField(default=False)),
                ('notes_on_failover', models.TextField(blank=True)),
                ('power_domains', models.ManyToManyField(blank=True, related_name='redundancy_groups', to='netbox_power_plant.powerdomain')),
                ('power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redundancy_groups', to='netbox_power_plant.powersystem')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'redundancy group',
                'verbose_name_plural': 'redundancy groups',
                'ordering': ('power_system__name', 'name'),
            },
            bases=(models.Model,),
        ),
        migrations.AddConstraint(
            model_name='powerdomain',
            constraint=models.UniqueConstraint(fields=('power_system', 'code'), name='netbox_power_plant_powerdomain_power_system_code'),
        ),
    ]
