# Generated by hand for phase 1B topology backbone.

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_power_plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('node_kind', models.CharField(default='custom', max_length=64)),
                ('equipment_role', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('install_state', models.CharField(default='planned', max_length=32)),
                ('topology_state', models.CharField(default='planned', max_length=32)),
                ('rated_input_voltage_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rated_input_voltage_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rated_output_voltage_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rated_output_voltage_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('frequency_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('phase_mode', models.CharField(default='3ph', max_length=16)),
                ('pole_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('installed_capacity_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usable_capacity_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('derating_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('reserve_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('telemetry_source_ref', models.CharField(blank=True, max_length=200)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_electrical_nodes', to='dcim.location')),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_nodes', to='netbox_power_plant.electricalnode')),
                ('power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_nodes', to='netbox_power_plant.powersystem')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_electrical_nodes', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'electrical node',
                'verbose_name_plural': 'electrical nodes',
                'ordering': ('power_system__name', 'site__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ElectricalTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('terminal_role', models.CharField(default='custom', max_length=32)),
                ('direction', models.CharField(default='bidirectional', max_length=16)),
                ('supply_type', models.CharField(default='ac', max_length=16)),
                ('voltage_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amperage_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('phase_designation', models.CharField(blank=True, max_length=32)),
                ('pole_designation', models.CharField(blank=True, max_length=32)),
                ('connector_type', models.CharField(blank=True, max_length=64)),
                ('is_protected', models.BooleanField(default=False)),
                ('is_switchable', models.BooleanField(default=False)),
                ('is_monitored', models.BooleanField(default=False)),
                ('position_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='netbox_power_plant.electricalnode')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'electrical terminal',
                'verbose_name_plural': 'electrical terminals',
                'ordering': ('node__name', 'position_index', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ElectricalSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('segment_kind', models.CharField(default='feeder', max_length=32)),
                ('path_state', models.CharField(default='planned', max_length=32)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conductor_material', models.CharField(blank=True, max_length=32)),
                ('conductor_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('awg_or_mm2', models.CharField(blank=True, max_length=32)),
                ('insulation_type', models.CharField(blank=True, max_length=32)),
                ('breaker_size_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('voltage_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ampacity_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('derated_ampacity_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('from_terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_segments', to='netbox_power_plant.electricalterminal')),
                ('power_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electrical_segments', to='netbox_power_plant.powerdomain')),
                ('power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_segments', to='netbox_power_plant.powersystem')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('to_terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_segments', to='netbox_power_plant.electricalterminal')),
            ],
            options={
                'verbose_name': 'electrical segment',
                'verbose_name_plural': 'electrical segments',
                'ordering': ('power_system__name', 'from_terminal__node__name', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='electricalterminal',
            constraint=models.UniqueConstraint(fields=('node', 'name'), name='netbox_power_plant_terminal_node_name'),
        ),
        migrations.AddConstraint(
            model_name='electricalsegment',
            constraint=models.UniqueConstraint(condition=models.Q(path_state='active'), fields=('from_terminal', 'to_terminal'), name='netbox_power_plant_active_segment_terminal_pair'),
        ),
    ]
