# Generated by hand for persisted rack-boundary delivery points.

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_power_plant', '0002_phase_1b_topology'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackDeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('delivery_role', models.CharField(blank=True, help_text='Operator-facing role for the handoff, such as primary, redundant, or maintenance.', max_length=100)),
                ('feed_label', models.CharField(blank=True, help_text='Short label such as A-feed, B-feed, or RPP-12-L21.', max_length=100)),
                ('design_state', models.CharField(default='planned', max_length=32)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_delivery_points', to='dcim.device')),
                ('electrical_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rack_delivery_points', to='netbox_power_plant.electricalnode')),
                ('electrical_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rack_delivery_points', to='netbox_power_plant.electricalterminal')),
                ('expected_redundancy_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rack_delivery_points', to='netbox_power_plant.redundancygroup')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_delivery_points', to='netbox_power_plant.powersystem')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_delivery_points', to='dcim.rack')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'rack delivery point',
                'verbose_name_plural': 'rack delivery points',
                'ordering': ('power_system__name', 'name'),
            },
        ),
    ]