# Generated by hand for persisted electrical node placement overlays.

import django.db.models.deletion
import taggit.managers
import utilities.fields
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_power_plant', '0003_rackdeliverypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalNodePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('placement_scope_type', models.CharField(default='location', max_length=16)),
                ('x', models.DecimalField(decimal_places=2, help_text='Horizontal floorplan coordinate in plugin-owned overlay space.', max_digits=10)),
                ('y', models.DecimalField(decimal_places=2, help_text='Vertical floorplan coordinate in plugin-owned overlay space.', max_digits=10)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rotation_degrees', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('symbol_kind', models.CharField(default='equipment', max_length=32)),
                ('label_mode', models.CharField(default='name', max_length=32)),
                ('color', utilities.fields.ColorField(blank=True, help_text='Optional color override for the rendered overlay symbol.', max_length=6)),
                ('z_index', models.PositiveIntegerField(default=100, help_text='Higher values render above lower-priority overlays.')),
                ('electrical_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='netbox_power_plant.electricalnode')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_node_placements', to='dcim.location')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_node_placements', to='netbox_power_plant.powersystem')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_node_placements', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'electrical node placement',
                'verbose_name_plural': 'electrical node placements',
                'ordering': ('power_system__name', 'electrical_node__name', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='electricalnodeplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('power_system', 'electrical_node', 'site', 'location'), name='netbox_power_plant_nodeplacement_unique_location_scope'),
        ),
        migrations.AddConstraint(
            model_name='electricalnodeplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('power_system', 'electrical_node', 'site'), name='netbox_power_plant_nodeplacement_unique_site_scope'),
        ),
    ]