# Generated by hand for rack-internal power bus modeling.

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_power_plant', '0005_rackdeliverypoint_power_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalPowerBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('bus_role', models.CharField(default='busbar', max_length=32)),
                ('supply_type', models.CharField(default='dc', max_length=16)),
                ('nominal_voltage', models.DecimalField(blank=True, decimal_places=2, help_text='Nominal bus voltage, expressed in volts.', max_digits=8, null=True)),
                ('design_state', models.CharField(default='planned', max_length=32)),
                ('power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_power_buses', to='netbox_power_plant.powersystem')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_internal_buses', to='dcim.rack')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'internal power bus',
                'verbose_name_plural': 'internal power buses',
                'ordering': ('power_system__name', 'rack__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InternalPowerBusAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('attachment_role', models.CharField(max_length=16)),
                ('position_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('design_state', models.CharField(default='planned', max_length=32)),
                ('internal_power_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='netbox_power_plant.internalpowerbus')),
                ('power_port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_internal_bus_attachments', to='dcim.powerport')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'internal power bus attachment',
                'verbose_name_plural': 'internal power bus attachments',
                'ordering': ('internal_power_bus__name', 'attachment_role', 'position_index', 'power_port__device__name', 'power_port__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='internalpowerbus',
            constraint=models.UniqueConstraint(fields=('rack', 'name'), name='netbox_power_plant_internalpowerbus_rack_name'),
        ),
        migrations.AddConstraint(
            model_name='internalpowerbusattachment',
            constraint=models.UniqueConstraint(fields=('internal_power_bus', 'power_port'), name='netbox_power_plant_internalpowerbusattachment_bus_port'),
        ),
    ]
