# Generated by hand for native spatial modeling.

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_power_plant', '0008_legacy_rackdeliverypoint_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('origin_x_in_parent', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('origin_y_in_parent', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('units', models.CharField(default='mad1_svg_unit', max_length=64)),
                ('axis_orientation', models.CharField(default='lower-left-x-right-y-up', max_length=64)),
                ('source_document', models.CharField(blank=True, max_length=200)),
                ('source_ref', models.CharField(blank=True, max_length=200)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_spatial_frames', to='dcim.location')),
                ('parent_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_frames', to='netbox_power_plant.spatialframe')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_spatial_frames', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'spatial frame',
                'verbose_name_plural': 'spatial frames',
                'ordering': ('site__name', 'location__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SpatialPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('assigned_object_id', models.PositiveBigIntegerField()),
                ('x', models.DecimalField(decimal_places=3, max_digits=12)),
                ('y', models.DecimalField(decimal_places=3, max_digits=12)),
                ('z', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('rotation_degrees', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('anchor', models.CharField(default='center', max_length=32)),
                ('placement_kind', models.CharField(default='physical', max_length=32)),
                ('confidence', models.CharField(default='unknown', max_length=32)),
                ('source_document', models.CharField(blank=True, max_length=200)),
                ('source_ref', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_spatial_placements', to='contenttypes.contenttype')),
                ('spatial_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='netbox_power_plant.spatialframe')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'spatial placement',
                'verbose_name_plural': 'spatial placements',
                'ordering': ('spatial_frame__site__name', 'spatial_frame__name', 'name'),
                'indexes': [models.Index(fields=['assigned_object_type', 'assigned_object_id'], name='nbpp_sp_place_obj')],
            },
        ),
    ]
