# Generated by hand for persisted validation findings.

import django.conf
import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_power_plant', '0009_spatial_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('run_kind', models.CharField(default='topology', max_length=32)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to='netbox_power_plant.powersystem')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'power validation run',
                'verbose_name_plural': 'power validation runs',
                'ordering': ('-started_at', '-created'),
            },
        ),
        migrations.CreateModel(
            name='PowerFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('fingerprint', models.CharField(max_length=64)),
                ('finding_type', models.CharField(max_length=100)),
                ('severity', models.CharField(default='warning', max_length=32)),
                ('status', models.CharField(default='open', max_length=32)),
                ('message', models.TextField()),
                ('assigned_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('suppressed_until', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('assigned_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_findings', to='contenttypes.contenttype')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_plant_findings', to=django.conf.settings.AUTH_USER_MODEL)),
                ('power_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_findings', to='netbox_power_plant.powersystem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='netbox_power_plant.powervalidationrun')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'power finding',
                'verbose_name_plural': 'power findings',
                'ordering': ('status', '-severity', 'finding_type', 'name'),
                'indexes': [
                    models.Index(fields=['assigned_object_type', 'assigned_object_id'], name='nbpp_finding_obj'),
                    models.Index(fields=['power_system', 'status', 'severity'], name='nbpp_finding_state'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='powerfinding',
            constraint=models.UniqueConstraint(fields=('run', 'fingerprint'), name='netbox_power_plant_finding_run_fingerprint'),
        ),
    ]
