# Generated by hand for neocloud capacity reservations and electrical node details.

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('netbox_power_plant', '0013_spatial_frame_confidence_metadata'),
        ('tenancy', '0017_natural_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='BESSDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('technology', models.CharField(blank=True, max_length=100)),
                ('energy_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('peak_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('charge_rate_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usable_soc_min_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('usable_soc_max_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='netbox_power_plant.electricalnode')),
            ],
            options={
                'verbose_name': 'BESS detail',
                'verbose_name_plural': 'BESS details',
                'ordering': ('node__power_system__name', 'node__name'),
            },
        ),
        migrations.CreateModel(
            name='GeneratorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(blank=True, max_length=100)),
                ('runtime_at_full_load_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cooling_type', models.CharField(blank=True, max_length=100)),
                ('ats_group_id', models.CharField(blank=True, max_length=100)),
                ('automatic_transfer_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='netbox_power_plant.electricalnode')),
            ],
            options={
                'verbose_name': 'generator detail',
                'verbose_name_plural': 'generator details',
                'ordering': ('node__power_system__name', 'node__name'),
            },
        ),
        migrations.CreateModel(
            name='TransformerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('primary_kv', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('secondary_kv', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('kva_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vector_group', models.CharField(blank=True, max_length=100)),
                ('impedance_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cooling_type', models.CharField(blank=True, max_length=100)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='netbox_power_plant.electricalnode')),
            ],
            options={
                'verbose_name': 'transformer detail',
                'verbose_name_plural': 'transformer details',
                'ordering': ('node__power_system__name', 'node__name'),
            },
        ),
        migrations.CreateModel(
            name='UPSDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ups_topology', models.CharField(blank=True, max_length=100)),
                ('battery_autonomy_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('module_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('module_rating_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parallel_group_id', models.CharField(blank=True, max_length=100)),
                ('maintenance_bypass_present', models.BooleanField(default=False)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='netbox_power_plant.electricalnode')),
            ],
            options={
                'verbose_name': 'UPS detail',
                'verbose_name_plural': 'UPS details',
                'ordering': ('node__power_system__name', 'node__name'),
            },
        ),
        migrations.CreateModel(
            name='BuswaySectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('section_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rated_ampacity_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('plug_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plug_spacing_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('busway_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='busway_sections', to='netbox_power_plant.electricalnode')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='netbox_power_plant.electricalnode')),
            ],
            options={
                'verbose_name': 'busway section detail',
                'verbose_name_plural': 'busway section details',
                'ordering': ('busway_system__name', 'section_index', 'node__name'),
            },
        ),
        migrations.CreateModel(
            name='CapacityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('reserved_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='planned', max_length=32)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_reservations', to='netbox_power_plant.electricalnode')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_capacity_reservations', to='dcim.rack')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_plant_capacity_reservations', to='tenancy.tenant')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'capacity reservation',
                'verbose_name_plural': 'capacity reservations',
                'ordering': ('node__power_system__name', 'node__name', 'status', 'valid_from', 'name'),
                'indexes': [
                    models.Index(fields=['node', 'status', 'valid_from', 'valid_until'], name='nbpp_capres_node_status'),
                    models.Index(fields=['tenant', 'status'], name='nbpp_capres_tenant_status'),
                    models.Index(fields=['rack', 'status'], name='nbpp_capres_rack_status'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='capacityreservation',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_kw__gt', 0)), name='netbox_power_plant_capacityreservation_reserved_kw_positive'),
        ),
    ]
