from django.urls import path

from .views import (
    ElectricalNodeDeleteView,
    ElectricalNodeEditView,
    ElectricalNodeListView,
    ElectricalNodePlacementDeleteView,
    ElectricalNodePlacementEditView,
    ElectricalNodePlacementListView,
    ElectricalNodePlacementView,
    ElectricalNodeView,
    ElectricalSegmentDeleteView,
    ElectricalSegmentEditView,
    ElectricalSegmentListView,
    ElectricalSegmentView,
    ElectricalTerminalDeleteView,
    ElectricalTerminalEditView,
    ElectricalTerminalListView,
    ElectricalTerminalView,
    HomeView,
    PowerDomainDeleteView,
    PowerDomainEditView,
    PowerDomainListView,
    PowerDomainView,
    RackDeliveryPointDeleteView,
    RackDeliveryPointEditView,
    RackDeliveryPointListView,
    RackDeliveryPointView,
    PowerSystemDeleteView,
    PowerSystemEditView,
    PowerSystemLayoutView,
    PowerSystemListView,
    PowerSystemRackDeliveryView,
    PowerSystemView,
    RedundancyGroupDeleteView,
    RedundancyGroupEditView,
    RedundancyGroupListView,
    RedundancyGroupView,
)


app_name = 'netbox_power_plant'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('power-systems/', PowerSystemListView.as_view(), name='powersystem_list'),
    path('power-systems/add/', PowerSystemEditView.as_view(), name='powersystem_add'),
    path('power-systems/<int:pk>/', PowerSystemView.as_view(), name='powersystem'),
    path('power-systems/<int:pk>/layout/', PowerSystemLayoutView.as_view(), name='powersystem_layout'),
    path('power-systems/<int:pk>/rack-delivery/', PowerSystemRackDeliveryView.as_view(), name='powersystem_rack_delivery'),
    path('power-systems/<int:pk>/edit/', PowerSystemEditView.as_view(), name='powersystem_edit'),
    path('power-systems/<int:pk>/delete/', PowerSystemDeleteView.as_view(), name='powersystem_delete'),
    path('power-domains/', PowerDomainListView.as_view(), name='powerdomain_list'),
    path('power-domains/add/', PowerDomainEditView.as_view(), name='powerdomain_add'),
    path('power-domains/<int:pk>/', PowerDomainView.as_view(), name='powerdomain'),
    path('power-domains/<int:pk>/edit/', PowerDomainEditView.as_view(), name='powerdomain_edit'),
    path('power-domains/<int:pk>/delete/', PowerDomainDeleteView.as_view(), name='powerdomain_delete'),
    path('redundancy-groups/', RedundancyGroupListView.as_view(), name='redundancygroup_list'),
    path('redundancy-groups/add/', RedundancyGroupEditView.as_view(), name='redundancygroup_add'),
    path('redundancy-groups/<int:pk>/', RedundancyGroupView.as_view(), name='redundancygroup'),
    path('redundancy-groups/<int:pk>/edit/', RedundancyGroupEditView.as_view(), name='redundancygroup_edit'),
    path('redundancy-groups/<int:pk>/delete/', RedundancyGroupDeleteView.as_view(), name='redundancygroup_delete'),
    path('electrical-nodes/', ElectricalNodeListView.as_view(), name='electricalnode_list'),
    path('electrical-nodes/add/', ElectricalNodeEditView.as_view(), name='electricalnode_add'),
    path('electrical-nodes/<int:pk>/', ElectricalNodeView.as_view(), name='electricalnode'),
    path('electrical-nodes/<int:pk>/edit/', ElectricalNodeEditView.as_view(), name='electricalnode_edit'),
    path('electrical-nodes/<int:pk>/delete/', ElectricalNodeDeleteView.as_view(), name='electricalnode_delete'),
    path('electrical-terminals/', ElectricalTerminalListView.as_view(), name='electricalterminal_list'),
    path('electrical-terminals/add/', ElectricalTerminalEditView.as_view(), name='electricalterminal_add'),
    path('electrical-terminals/<int:pk>/', ElectricalTerminalView.as_view(), name='electricalterminal'),
    path('electrical-terminals/<int:pk>/edit/', ElectricalTerminalEditView.as_view(), name='electricalterminal_edit'),
    path('electrical-terminals/<int:pk>/delete/', ElectricalTerminalDeleteView.as_view(), name='electricalterminal_delete'),
    path('electrical-segments/', ElectricalSegmentListView.as_view(), name='electricalsegment_list'),
    path('electrical-segments/add/', ElectricalSegmentEditView.as_view(), name='electricalsegment_add'),
    path('electrical-segments/<int:pk>/', ElectricalSegmentView.as_view(), name='electricalsegment'),
    path('electrical-segments/<int:pk>/edit/', ElectricalSegmentEditView.as_view(), name='electricalsegment_edit'),
    path('electrical-segments/<int:pk>/delete/', ElectricalSegmentDeleteView.as_view(), name='electricalsegment_delete'),
    path('rack-delivery-points/', RackDeliveryPointListView.as_view(), name='rackdeliverypoint_list'),
    path('rack-delivery-points/add/', RackDeliveryPointEditView.as_view(), name='rackdeliverypoint_add'),
    path('rack-delivery-points/<int:pk>/', RackDeliveryPointView.as_view(), name='rackdeliverypoint'),
    path('rack-delivery-points/<int:pk>/edit/', RackDeliveryPointEditView.as_view(), name='rackdeliverypoint_edit'),
    path('rack-delivery-points/<int:pk>/delete/', RackDeliveryPointDeleteView.as_view(), name='rackdeliverypoint_delete'),
    path('electrical-node-placements/', ElectricalNodePlacementListView.as_view(), name='electricalnodeplacement_list'),
    path('electrical-node-placements/add/', ElectricalNodePlacementEditView.as_view(), name='electricalnodeplacement_add'),
    path('electrical-node-placements/<int:pk>/', ElectricalNodePlacementView.as_view(), name='electricalnodeplacement'),
    path('electrical-node-placements/<int:pk>/edit/', ElectricalNodePlacementEditView.as_view(), name='electricalnodeplacement_edit'),
    path('electrical-node-placements/<int:pk>/delete/', ElectricalNodePlacementDeleteView.as_view(), name='electricalnodeplacement_delete'),
]
