from django.urls import path

from .views import (
    BESSDetailDeleteView,
    BESSDetailEditView,
    BESSDetailListView,
    BESSDetailView,
    BuswaySectionDetailDeleteView,
    BuswaySectionDetailEditView,
    BuswaySectionDetailListView,
    BuswaySectionDetailView,
    CapacityReservationDeleteView,
    CapacityReservationEditView,
    CapacityReservationListView,
    CapacityReservationView,
    ElectricalNodeDeleteView,
    ElectricalNodeEditView,
    ElectricalNodeListView,
    ElectricalNodePlacementDeleteView,
    ElectricalNodePlacementEditView,
    ElectricalNodePlacementListView,
    ElectricalNodePlacementView,
    ElectricalNodeView,
    ElectricalSegmentDeleteView,
    ElectricalSegmentEditView,
    ElectricalSegmentListView,
    ElectricalSegmentView,
    ElectricalTerminalDeleteView,
    ElectricalTerminalEditView,
    ElectricalTerminalListView,
    ElectricalTerminalView,
    GeneratorDetailDeleteView,
    GeneratorDetailEditView,
    GeneratorDetailListView,
    GeneratorDetailView,
    HomeView,
    InstantiationArtifactListView,
    InstantiationArtifactView,
    InstantiationRunListView,
    InstantiationRunView,
    InternalPowerBusAttachmentDeleteView,
    InternalPowerBusAttachmentEditView,
    InternalPowerBusAttachmentListView,
    InternalPowerBusAttachmentView,
    InternalPowerBusDeleteView,
    InternalPowerBusEditView,
    InternalPowerBusListView,
    InternalPowerBusView,
    MadisonUnderlayReviewView,
    NeocloudCockpitView,
    PhysicalElementDeleteView,
    PhysicalElementEditView,
    PhysicalElementListView,
    PhysicalElementTypeDeleteView,
    PhysicalElementTypeEditView,
    PhysicalElementTypeListView,
    PhysicalElementTypeView,
    PhysicalElementView,
    PhysicalObjectBindingDeleteView,
    PhysicalObjectBindingEditView,
    PhysicalObjectBindingListView,
    PhysicalObjectBindingView,
    PhysicalSpaceDeleteView,
    PhysicalSpaceEditView,
    PhysicalSpaceListView,
    PhysicalSpaceView,
    PlantProvenanceDeleteView,
    PlantProvenanceEditView,
    PlantProvenanceListView,
    PlantProvenanceView,
    PlantSourceDocumentDeleteView,
    PlantSourceDocumentEditView,
    PlantSourceDocumentListView,
    PlantSourceDocumentView,
    PlantSourceLayerDeleteView,
    PlantSourceLayerEditView,
    PlantSourceLayerListView,
    PlantSourceLayerView,
    PlantSourceSheetDeleteView,
    PlantSourceSheetEditView,
    PlantSourceSheetListView,
    PlantSourceSheetView,
    PowerDomainDeleteView,
    PowerDomainEditView,
    PowerDomainListView,
    PowerDomainView,
    OperatorDashboardView,
    PowerFindingDeleteView,
    PowerFindingEditView,
    PowerFindingListView,
    PowerFindingView,
    PowerHandoffPointDeleteView,
    PowerHandoffPointEditView,
    PowerHandoffPointListView,
    PowerHandoffPointView,
    PowerArchitectureTemplateListView,
    PowerArchitectureTemplateView,
    PowerSystemDeleteView,
    PowerSystemEditView,
    PowerSystemLayoutView,
    PowerSystemListView,
    PowerSystemPowerHandoffSummaryView,
    PowerSystemValidationActionView,
    PowerSystemView,
    PowerValidationRunDeleteView,
    PowerValidationRunEditView,
    PowerValidationRunListView,
    PowerValidationRunView,
    RedundancyGroupDeleteView,
    RedundancyGroupEditView,
    RedundancyGroupListView,
    RedundancyGroupView,
    SpatialFrameDeleteView,
    SpatialFrameEditView,
    SpatialFrameListView,
    SpatialFrameView,
    SpatialPlacementDeleteView,
    SpatialPlacementEditView,
    SpatialPlacementListView,
    SpatialPlacementView,
    TemplateWorkflowView,
    TransformerDetailDeleteView,
    TransformerDetailEditView,
    TransformerDetailListView,
    TransformerDetailView,
    UPSDetailDeleteView,
    UPSDetailEditView,
    UPSDetailListView,
    UPSDetailView,
)


app_name = 'netbox_power_plant'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('operator-center/', OperatorDashboardView.as_view(), name='operator_dashboard'),
    path('neocloud-cockpit/', NeocloudCockpitView.as_view(), name='neocloud_cockpit'),
    path('template-workflow/', TemplateWorkflowView.as_view(), name='template_workflow'),
    path('madison-underlay-review/', MadisonUnderlayReviewView.as_view(), name='madison_underlay_review'),
    path('architecture-templates/', PowerArchitectureTemplateListView.as_view(), name='powerarchitecturetemplate_list'),
    path('architecture-templates/<int:pk>/', PowerArchitectureTemplateView.as_view(), name='powerarchitecturetemplate'),
    path('instantiation-runs/', InstantiationRunListView.as_view(), name='instantiationrun_list'),
    path('instantiation-runs/<int:pk>/', InstantiationRunView.as_view(), name='instantiationrun'),
    path('instantiation-artifacts/', InstantiationArtifactListView.as_view(), name='instantiationartifact_list'),
    path('instantiation-artifacts/<int:pk>/', InstantiationArtifactView.as_view(), name='instantiationartifact'),
    path('power-systems/', PowerSystemListView.as_view(), name='powersystem_list'),
    path('power-systems/add/', PowerSystemEditView.as_view(), name='powersystem_add'),
    path('power-systems/<int:pk>/', PowerSystemView.as_view(), name='powersystem'),
    path('power-systems/<int:pk>/layout/', PowerSystemLayoutView.as_view(), name='powersystem_layout'),
    path('power-systems/<int:pk>/rack-delivery/', PowerSystemPowerHandoffSummaryView.as_view(), name='powersystem_rack_delivery'),
    path(
        'power-systems/<int:pk>/validate/<str:run_kind>/',
        PowerSystemValidationActionView.as_view(),
        name='powersystem_validation_action',
    ),
    path('power-systems/<int:pk>/edit/', PowerSystemEditView.as_view(), name='powersystem_edit'),
    path('power-systems/<int:pk>/delete/', PowerSystemDeleteView.as_view(), name='powersystem_delete'),
    path('power-domains/', PowerDomainListView.as_view(), name='powerdomain_list'),
    path('power-domains/add/', PowerDomainEditView.as_view(), name='powerdomain_add'),
    path('power-domains/<int:pk>/', PowerDomainView.as_view(), name='powerdomain'),
    path('power-domains/<int:pk>/edit/', PowerDomainEditView.as_view(), name='powerdomain_edit'),
    path('power-domains/<int:pk>/delete/', PowerDomainDeleteView.as_view(), name='powerdomain_delete'),
    path('validation-runs/', PowerValidationRunListView.as_view(), name='powervalidationrun_list'),
    path('validation-runs/add/', PowerValidationRunEditView.as_view(), name='powervalidationrun_add'),
    path('validation-runs/<int:pk>/', PowerValidationRunView.as_view(), name='powervalidationrun'),
    path('validation-runs/<int:pk>/edit/', PowerValidationRunEditView.as_view(), name='powervalidationrun_edit'),
    path('validation-runs/<int:pk>/delete/', PowerValidationRunDeleteView.as_view(), name='powervalidationrun_delete'),
    path('findings/', PowerFindingListView.as_view(), name='powerfinding_list'),
    path('findings/add/', PowerFindingEditView.as_view(), name='powerfinding_add'),
    path('findings/<int:pk>/', PowerFindingView.as_view(), name='powerfinding'),
    path('findings/<int:pk>/edit/', PowerFindingEditView.as_view(), name='powerfinding_edit'),
    path('findings/<int:pk>/delete/', PowerFindingDeleteView.as_view(), name='powerfinding_delete'),
    path('redundancy-groups/', RedundancyGroupListView.as_view(), name='redundancygroup_list'),
    path('redundancy-groups/add/', RedundancyGroupEditView.as_view(), name='redundancygroup_add'),
    path('redundancy-groups/<int:pk>/', RedundancyGroupView.as_view(), name='redundancygroup'),
    path('redundancy-groups/<int:pk>/edit/', RedundancyGroupEditView.as_view(), name='redundancygroup_edit'),
    path('redundancy-groups/<int:pk>/delete/', RedundancyGroupDeleteView.as_view(), name='redundancygroup_delete'),
    path('electrical-nodes/', ElectricalNodeListView.as_view(), name='electricalnode_list'),
    path('electrical-nodes/add/', ElectricalNodeEditView.as_view(), name='electricalnode_add'),
    path('electrical-nodes/<int:pk>/', ElectricalNodeView.as_view(), name='electricalnode'),
    path('electrical-nodes/<int:pk>/edit/', ElectricalNodeEditView.as_view(), name='electricalnode_edit'),
    path('electrical-nodes/<int:pk>/delete/', ElectricalNodeDeleteView.as_view(), name='electricalnode_delete'),
    path('electrical-terminals/', ElectricalTerminalListView.as_view(), name='electricalterminal_list'),
    path('electrical-terminals/add/', ElectricalTerminalEditView.as_view(), name='electricalterminal_add'),
    path('electrical-terminals/<int:pk>/', ElectricalTerminalView.as_view(), name='electricalterminal'),
    path('electrical-terminals/<int:pk>/edit/', ElectricalTerminalEditView.as_view(), name='electricalterminal_edit'),
    path('electrical-terminals/<int:pk>/delete/', ElectricalTerminalDeleteView.as_view(), name='electricalterminal_delete'),
    path('electrical-segments/', ElectricalSegmentListView.as_view(), name='electricalsegment_list'),
    path('electrical-segments/add/', ElectricalSegmentEditView.as_view(), name='electricalsegment_add'),
    path('electrical-segments/<int:pk>/', ElectricalSegmentView.as_view(), name='electricalsegment'),
    path('electrical-segments/<int:pk>/edit/', ElectricalSegmentEditView.as_view(), name='electricalsegment_edit'),
    path('electrical-segments/<int:pk>/delete/', ElectricalSegmentDeleteView.as_view(), name='electricalsegment_delete'),
    path('power-handoff-points/', PowerHandoffPointListView.as_view(), name='powerhandoffpoint_list'),
    path('power-handoff-points/add/', PowerHandoffPointEditView.as_view(), name='powerhandoffpoint_add'),
    path('power-handoff-points/<int:pk>/', PowerHandoffPointView.as_view(), name='powerhandoffpoint'),
    path('power-handoff-points/<int:pk>/edit/', PowerHandoffPointEditView.as_view(), name='powerhandoffpoint_edit'),
    path('power-handoff-points/<int:pk>/delete/', PowerHandoffPointDeleteView.as_view(), name='powerhandoffpoint_delete'),
    path('capacity-reservations/', CapacityReservationListView.as_view(), name='capacityreservation_list'),
    path('capacity-reservations/add/', CapacityReservationEditView.as_view(), name='capacityreservation_add'),
    path('capacity-reservations/<int:pk>/', CapacityReservationView.as_view(), name='capacityreservation'),
    path('capacity-reservations/<int:pk>/edit/', CapacityReservationEditView.as_view(), name='capacityreservation_edit'),
    path('capacity-reservations/<int:pk>/delete/', CapacityReservationDeleteView.as_view(), name='capacityreservation_delete'),
    path('ups-details/', UPSDetailListView.as_view(), name='upsdetail_list'),
    path('ups-details/add/', UPSDetailEditView.as_view(), name='upsdetail_add'),
    path('ups-details/<int:pk>/', UPSDetailView.as_view(), name='upsdetail'),
    path('ups-details/<int:pk>/edit/', UPSDetailEditView.as_view(), name='upsdetail_edit'),
    path('ups-details/<int:pk>/delete/', UPSDetailDeleteView.as_view(), name='upsdetail_delete'),
    path('generator-details/', GeneratorDetailListView.as_view(), name='generatordetail_list'),
    path('generator-details/add/', GeneratorDetailEditView.as_view(), name='generatordetail_add'),
    path('generator-details/<int:pk>/', GeneratorDetailView.as_view(), name='generatordetail'),
    path('generator-details/<int:pk>/edit/', GeneratorDetailEditView.as_view(), name='generatordetail_edit'),
    path('generator-details/<int:pk>/delete/', GeneratorDetailDeleteView.as_view(), name='generatordetail_delete'),
    path('transformer-details/', TransformerDetailListView.as_view(), name='transformerdetail_list'),
    path('transformer-details/add/', TransformerDetailEditView.as_view(), name='transformerdetail_add'),
    path('transformer-details/<int:pk>/', TransformerDetailView.as_view(), name='transformerdetail'),
    path('transformer-details/<int:pk>/edit/', TransformerDetailEditView.as_view(), name='transformerdetail_edit'),
    path('transformer-details/<int:pk>/delete/', TransformerDetailDeleteView.as_view(), name='transformerdetail_delete'),
    path('bess-details/', BESSDetailListView.as_view(), name='bessdetail_list'),
    path('bess-details/add/', BESSDetailEditView.as_view(), name='bessdetail_add'),
    path('bess-details/<int:pk>/', BESSDetailView.as_view(), name='bessdetail'),
    path('bess-details/<int:pk>/edit/', BESSDetailEditView.as_view(), name='bessdetail_edit'),
    path('bess-details/<int:pk>/delete/', BESSDetailDeleteView.as_view(), name='bessdetail_delete'),
    path('busway-section-details/', BuswaySectionDetailListView.as_view(), name='buswaysectiondetail_list'),
    path('busway-section-details/add/', BuswaySectionDetailEditView.as_view(), name='buswaysectiondetail_add'),
    path('busway-section-details/<int:pk>/', BuswaySectionDetailView.as_view(), name='buswaysectiondetail'),
    path('busway-section-details/<int:pk>/edit/', BuswaySectionDetailEditView.as_view(), name='buswaysectiondetail_edit'),
    path('busway-section-details/<int:pk>/delete/', BuswaySectionDetailDeleteView.as_view(), name='buswaysectiondetail_delete'),
    path('internal-power-buses/', InternalPowerBusListView.as_view(), name='internalpowerbus_list'),
    path('internal-power-buses/add/', InternalPowerBusEditView.as_view(), name='internalpowerbus_add'),
    path('internal-power-buses/<int:pk>/', InternalPowerBusView.as_view(), name='internalpowerbus'),
    path('internal-power-buses/<int:pk>/edit/', InternalPowerBusEditView.as_view(), name='internalpowerbus_edit'),
    path('internal-power-buses/<int:pk>/delete/', InternalPowerBusDeleteView.as_view(), name='internalpowerbus_delete'),
    path('internal-power-bus-attachments/', InternalPowerBusAttachmentListView.as_view(), name='internalpowerbusattachment_list'),
    path('internal-power-bus-attachments/add/', InternalPowerBusAttachmentEditView.as_view(), name='internalpowerbusattachment_add'),
    path('internal-power-bus-attachments/<int:pk>/', InternalPowerBusAttachmentView.as_view(), name='internalpowerbusattachment'),
    path('internal-power-bus-attachments/<int:pk>/edit/', InternalPowerBusAttachmentEditView.as_view(), name='internalpowerbusattachment_edit'),
    path('internal-power-bus-attachments/<int:pk>/delete/', InternalPowerBusAttachmentDeleteView.as_view(), name='internalpowerbusattachment_delete'),
    path('plant-source-documents/', PlantSourceDocumentListView.as_view(), name='plantsourcedocument_list'),
    path('plant-source-documents/add/', PlantSourceDocumentEditView.as_view(), name='plantsourcedocument_add'),
    path('plant-source-documents/<int:pk>/', PlantSourceDocumentView.as_view(), name='plantsourcedocument'),
    path('plant-source-documents/<int:pk>/edit/', PlantSourceDocumentEditView.as_view(), name='plantsourcedocument_edit'),
    path('plant-source-documents/<int:pk>/delete/', PlantSourceDocumentDeleteView.as_view(), name='plantsourcedocument_delete'),
    path('plant-source-sheets/', PlantSourceSheetListView.as_view(), name='plantsourcesheet_list'),
    path('plant-source-sheets/add/', PlantSourceSheetEditView.as_view(), name='plantsourcesheet_add'),
    path('plant-source-sheets/<int:pk>/', PlantSourceSheetView.as_view(), name='plantsourcesheet'),
    path('plant-source-sheets/<int:pk>/edit/', PlantSourceSheetEditView.as_view(), name='plantsourcesheet_edit'),
    path('plant-source-sheets/<int:pk>/delete/', PlantSourceSheetDeleteView.as_view(), name='plantsourcesheet_delete'),
    path('plant-source-layers/', PlantSourceLayerListView.as_view(), name='plantsourcelayer_list'),
    path('plant-source-layers/add/', PlantSourceLayerEditView.as_view(), name='plantsourcelayer_add'),
    path('plant-source-layers/<int:pk>/', PlantSourceLayerView.as_view(), name='plantsourcelayer'),
    path('plant-source-layers/<int:pk>/edit/', PlantSourceLayerEditView.as_view(), name='plantsourcelayer_edit'),
    path('plant-source-layers/<int:pk>/delete/', PlantSourceLayerDeleteView.as_view(), name='plantsourcelayer_delete'),
    path('plant-provenance/', PlantProvenanceListView.as_view(), name='plantprovenance_list'),
    path('plant-provenance/add/', PlantProvenanceEditView.as_view(), name='plantprovenance_add'),
    path('plant-provenance/<int:pk>/', PlantProvenanceView.as_view(), name='plantprovenance'),
    path('plant-provenance/<int:pk>/edit/', PlantProvenanceEditView.as_view(), name='plantprovenance_edit'),
    path('plant-provenance/<int:pk>/delete/', PlantProvenanceDeleteView.as_view(), name='plantprovenance_delete'),
    path('physical-spaces/', PhysicalSpaceListView.as_view(), name='physicalspace_list'),
    path('physical-spaces/add/', PhysicalSpaceEditView.as_view(), name='physicalspace_add'),
    path('physical-spaces/<int:pk>/', PhysicalSpaceView.as_view(), name='physicalspace'),
    path('physical-spaces/<int:pk>/edit/', PhysicalSpaceEditView.as_view(), name='physicalspace_edit'),
    path('physical-spaces/<int:pk>/delete/', PhysicalSpaceDeleteView.as_view(), name='physicalspace_delete'),
    path('physical-element-types/', PhysicalElementTypeListView.as_view(), name='physicalelementtype_list'),
    path('physical-element-types/add/', PhysicalElementTypeEditView.as_view(), name='physicalelementtype_add'),
    path('physical-element-types/<int:pk>/', PhysicalElementTypeView.as_view(), name='physicalelementtype'),
    path('physical-element-types/<int:pk>/edit/', PhysicalElementTypeEditView.as_view(), name='physicalelementtype_edit'),
    path('physical-element-types/<int:pk>/delete/', PhysicalElementTypeDeleteView.as_view(), name='physicalelementtype_delete'),
    path('physical-elements/', PhysicalElementListView.as_view(), name='physicalelement_list'),
    path('physical-elements/add/', PhysicalElementEditView.as_view(), name='physicalelement_add'),
    path('physical-elements/<int:pk>/', PhysicalElementView.as_view(), name='physicalelement'),
    path('physical-elements/<int:pk>/edit/', PhysicalElementEditView.as_view(), name='physicalelement_edit'),
    path('physical-elements/<int:pk>/delete/', PhysicalElementDeleteView.as_view(), name='physicalelement_delete'),
    path('physical-object-bindings/', PhysicalObjectBindingListView.as_view(), name='physicalobjectbinding_list'),
    path('physical-object-bindings/add/', PhysicalObjectBindingEditView.as_view(), name='physicalobjectbinding_add'),
    path('physical-object-bindings/<int:pk>/', PhysicalObjectBindingView.as_view(), name='physicalobjectbinding'),
    path('physical-object-bindings/<int:pk>/edit/', PhysicalObjectBindingEditView.as_view(), name='physicalobjectbinding_edit'),
    path('physical-object-bindings/<int:pk>/delete/', PhysicalObjectBindingDeleteView.as_view(), name='physicalobjectbinding_delete'),
    path('spatial-frames/', SpatialFrameListView.as_view(), name='spatialframe_list'),
    path('spatial-frames/add/', SpatialFrameEditView.as_view(), name='spatialframe_add'),
    path('spatial-frames/<int:pk>/', SpatialFrameView.as_view(), name='spatialframe'),
    path('spatial-frames/<int:pk>/edit/', SpatialFrameEditView.as_view(), name='spatialframe_edit'),
    path('spatial-frames/<int:pk>/delete/', SpatialFrameDeleteView.as_view(), name='spatialframe_delete'),
    path('spatial-placements/', SpatialPlacementListView.as_view(), name='spatialplacement_list'),
    path('spatial-placements/add/', SpatialPlacementEditView.as_view(), name='spatialplacement_add'),
    path('spatial-placements/<int:pk>/', SpatialPlacementView.as_view(), name='spatialplacement'),
    path('spatial-placements/<int:pk>/edit/', SpatialPlacementEditView.as_view(), name='spatialplacement_edit'),
    path('spatial-placements/<int:pk>/delete/', SpatialPlacementDeleteView.as_view(), name='spatialplacement_delete'),
    path('electrical-node-placements/', ElectricalNodePlacementListView.as_view(), name='electricalnodeplacement_list'),
    path('electrical-node-placements/add/', ElectricalNodePlacementEditView.as_view(), name='electricalnodeplacement_add'),
    path('electrical-node-placements/<int:pk>/', ElectricalNodePlacementView.as_view(), name='electricalnodeplacement'),
    path('electrical-node-placements/<int:pk>/edit/', ElectricalNodePlacementEditView.as_view(), name='electricalnodeplacement_edit'),
    path('electrical-node-placements/<int:pk>/delete/', ElectricalNodePlacementDeleteView.as_view(), name='electricalnodeplacement_delete'),
]
